In [1]:
#import library
import numpy as np
import scipy as sc

In [2]:
#difine coefficient matrix A
A=np.array([[2,4,6],[5,3,2],[7,8,9]])

In [3]:
print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [4]:
#Define constant vector b
b=np.array([[18],[13],[30]])

In [5]:
print(b)

[[18]
 [13]
 [30]]


In [6]:
#use solve 
C=sc.linalg.inv(A).dot(b)

In [7]:
print(C)

[[ 4.5]
 [-7.5]
 [ 6.5]]
